name: 'Cells Set up environment'
description: 'Set up build environment for Cells'
inputs:
  configure-npm:
    description: 'Flag to configure npm'
    required: false
    default: 'true'
  configure-gradle:
    description: 'Flag to configure gradle'
    required: false
    default: 'true'
  configure-bower:
    description: 'Flag to configure bower'
    required: false
    default: 'true'
  repository-npm:
    description: 'Repository to use for npm'
    required: false
    default: 'gl-bbva-npm-virtual'
  repository-bower:
    description: 'Repository to use for npm'
    required: false
    default: 'gl-bbva-npm-virtual'
  repository-gradle:
    description: 'Repository to use for npm'
    required: false
    default: 'gl-bbva-npm-virtual'
  artifactory-user:
    description: 'Artifactory User'
    required: true
  artifactory-password:
    description: 'Artifactory User'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
