name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    environment: Testing
    runs-on: ubuntu-latest
    container:
      image: artifactory.globaldevtools.bbva.com:443/gl-cells-docker-local/cells/arch/cells_devops/cicd-cells-k8s:cells-4.2.0
      credentials:
        username: andres.bitrian.tech
        password: ${{ secrets.ARTIFACTORY_TOKEN }}
      options: --cpus 1 --memory 4g --user root
    steps:
      - name: Checkout
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          pwd
          git clone https://$PAT@github.com/abitrian/test-component-lit.git
      